#!/usr/bin/env bash

################################################################################
# Runs performance benchmark tests using asv
#
# Usage:
#     check/asv_run [--flags for asv run]
################################################################################

# Get the working directory to the repo root.
thisdir=$(dirname "${BASH_SOURCE[0]:?}") || exit $?
repo_dir=$(git -C "${thisdir}" rev-parse --show-toplevel) || exit $?
cd "${repo_dir}" || exit $?

asv run "$@"
