#!/usr/bin/env bash

################################################################################
# Runs performance benchmark tests using asv
#
# Usage:
#     check/asv [--flags for asv]
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

export ASV_PYTHONPATH="$(git rev-parse --show-toplevel)/examples"
asv run $@