#!/usr/bin/env bash

################################################################################
# Runs bazel build for proto files in Cirq/cirq/google/api/*
#
# Usage:
#     check/bazel
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

bazel build //cirq/google/api/v1:operations_proto
bazel build //cirq/google/api/v1:params_proto
bazel build //cirq/google/api/v1:program_proto

bazel build //cirq/google/api/v2:metrics_proto
bazel build //cirq/google/api/v2:program_proto
bazel build //cirq/google/api/v2:run_context_proto
bazel build //cirq/google/api/v2:result_proto
