#!/usr/bin/env bash

################################################################################
# Runs custom lint checks on the Cirq repository.
#
# TODO(philiptmassey): Add more desciption
################################################################################

# TODO(philiptmassey): Enable this
# python dev_tools/custom_lint.py
