#!/usr/bin/env bash

################################################################################
# Runs python doctest on python source files in the repository.
#
# See also:
#     https://docs.python.org/3/library/doctest.html
#
# Usage:
#     check/doctest
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

python_source_files=(`find . | grep "\.py$"`)
python -m doctest "${python_source_files[@]}"
