#!/usr/bin/env bash

################################################################################
# Runs flynt on the repository
#
# Usage:
#     check/flynt [--flags for flynt]
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

flynt $@ cirq dev_tools examples -f
