#!/usr/bin/env bash

################################################################################
# Runs pylint on the repository using a preconfigured .pylintrc file.
# Runs flynt
#
# Usage:
#     check/lint [--flags for pylint]
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

pylint --rcfile=dev_tools/conf/.pylintrc $@ cirq dev_tools examples
flynt cirq dev_tools examples -f -q -d -e cirq/ops/pauli_string.py
