#!/usr/bin/env bash

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Runs markdownlint recursively from the top of the source tree.
#
# Note: there are multiple programs programs named "markdownlint". For Cirq,
# we use https://github.com/igorshubovych/markdownlint-cli/, which is the one
# you get with "brew install markdownlint" on MacOS.
#
# Usage:
#     check/markdownlint [--flags for markdownlint]
#
# This script assumes the markdownlint configuration file .markdownlint.yaml
# is located at the top of the Cirq source tree.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Get the working directory to the repo root.
thisdir="$(dirname "${BASH_SOURCE[0]}")" || exit $?
topdir="$(git -C "${thisdir}" rev-parse --show-toplevel)" || exit $?
cd "${topdir}" || exit $?

markdownlint "${@:-.}"
