#!/usr/bin/env bash

################################################################################
# Runs performance tests
#
# Usage:
#     check/performance
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $(git rev-parse --show-toplevel)

pytest --benchmark-autosave --benchmark-only && cd .benchmarks/Linux-CPython-3.6-64bit/ && ls -t | tail -n +3 | xargs rm -- && ls
