#!/usr/bin/env bash

################################################################################
# Runs pylint on the repository.
#
# Usage:
#     check/pylint [--flags for pylint]
################################################################################

# Get the working directory to the repo root.
thisdir=$(dirname "${BASH_SOURCE[0]:?}") || exit $?
repo_dir=$(git -C "${thisdir}" rev-parse --show-toplevel) || exit $?
cd "${repo_dir}" || exit $?

source dev_tools/pypath || exit $?
pylint --jobs=0 "$@" .
