#!/usr/bin/env bash

################################################################################
# Runs pytest on the repository.
#
# Usage:
#     check/pytest [--flags for pytest] [file-paths-relative-to-repo-root]
#
# You may specify pytest flags and specific files to test. The file paths
# must be relative to the repository root. If no files are specified, everything
# is tested.
################################################################################

# Get the working directory to the repo root.
cd "$(dirname "${BASH_SOURCE[0]}")"
cd "$(git rev-parse --show-toplevel)"

PYTEST_ARGS=()
# TODO(#5870) - remove this after fixing order-related test failures
PYTEST_ARGS+=("--randomly-dont-reorganize")

PARALLEL=""
for arg in "$@"; do
    if [[ "${arg}" == "-n" ]]; then
	PARALLEL=1
    fi
    PYTEST_ARGS+=("${arg}")
done

if [ -z "${PARALLEL}" ]; then
    PYTEST_ARGS+=("-n=auto")
fi

source dev_tools/pypath
PYTHON_VERSION=$(python -V 2>&1 | sed 's/.* \([0-9]\).\([0-9]\).*/\1\2/')
if [ "$PYTHON_VERSION" -lt "37" ]; then
  PYTEST_ARGS+=("--ignore=cirq-rigetti")
fi

pytest "${PYTEST_ARGS[@]}"
RESULT=$?

if [ "$RESULT" = 5 ]; then
  echo "[exit 5] No tests collected, but ignored."
  exit 0
fi

exit "$RESULT"
