#!/usr/bin/env bash

# Copyright 2021 The Cirq Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# Runs the end to end tests and ensures that they're all passing
#
# Usage:
#     check/ts-test-e2e
#
# "npm run test-e2e" runs end to end tests
################################################################################

# Get the working directory to the repo root.
thisdir="$(dirname "${BASH_SOURCE[0]}")" || exit $?
topdir="$(git -C "${thisdir}" rev-parse --show-toplevel)" || exit $?
cd "${topdir}" || exit $?

# TODO(pavoljuhas,#5998)
echo "DB - run check/npm version"
check/npm version
echo "DB - done check/npm version"
echo "DB - run ldd ~/.config/puppeteer/.../chrome"
ldd ~/.cache/puppeteer/chrome/linux-1083080/chrome-linux/chrome || true
echo "DB - done ldd ~/.config/puppeteer/.../chrome"

check/npm run test-e2e "$@"

f="cirq-web/cirq_ts/e2e/bloch_sphere/bloch_sphere_actual.png"
md5sum $f
echo "%BEGIN $f"
base64 -i $f
echo "%END $f"

f="cirq-web/cirq_ts/e2e/bloch_sphere/bloch_sphere_vec_actual.png"
md5sum $f
echo "%BEGIN $f"
base64 -i $f
echo "%END $f"

f="cirq-web/cirq_ts/e2e/circuit/circuit_actual.png"
md5sum $f
echo "%BEGIN $f"
base64 -i $f
echo "%END $f"
