# Copyright 2025 The Cirq Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# See https://yamllint.readthedocs.io/ for info about configuration options.
# IMPORTANT: if you change values here, update .editorconfig to match.

# Relaxed rules mean certain things like line lengths are warnings, not errors.
extends: relaxed

rules:
  line-length:
    # Match our code line length.
    max: 100
    # Long URLs are common. There's no setting for long URLs specifically, but
    # we can reduce some linter errors (and developer time) with the following.
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Require 2-space indentation.
  indentation:
    indent-sequences: true
    level: error
    spaces: 2

  # Require comment indentation to match code indentation.
  comments-indentation: enable
