# Summary: yamllint configuration for Cirq.
# See https://yamllint.readthedocs.io/ for info about configuration options.

rules:
  line-length:
    # YAML files (especially GitHub Actions workflows) tend to end up with
    # long lines. The default of 80 is pretty limiting, and besides, in Python
    # code linting, we set line lengths to 100. May as well follow suit here.
    max: 100
    # Another common occurrence in YAML files is long URLs. The next two
    # settings are not specific to URLs, but help. It saves developer time by
    # not requiring comment directives to disable warnings at every occurrence.
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
