# Custom style overrides for Cirq's Triage Party web site.

apiVersion: v1
kind: ConfigMap
metadata:
  name: cirq-triage-party-css
  namespace: triage-party
data:
  custom.css: |
    /* Put more space between the logo and the title text. */
    img[alt="logo"] { margin-left: 10px !important; }

    /* Change the color of the navbar to be the QAI blue. */
    .navbar, .navbar-menu { background-color: #2d53b8; }
    .navbar-item { background-color: #2d53b8; }

    /* Change the look & feel of the description box. */
    pre, code { font-family: system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif !important; white-space: normal !important; background-color: #fbf1c3 !important; color: #333 !important; }

    /* Adjust the look & feel of the data tables. */
    .section { display: flex; flex-direction: column; min-height: 100vh; background-color: #fff; }
    .section-title, .stat-title, .stats { color: #333 !important; }
    .subtitle { color: #666666 !important; }
    .is-active { background-color: #4d73d8 !important; }
    section:first-of-type { flex-grow: 1; }
    .box-header { background-color: #dddddf; color: #222; }
    .dataTables_filter label { color: #2f2f2f; }
    .hd { background-color: #eeeeee; color: #222; }
    nav, section:last-of-type { flex-shrink: 0; }

    /* Hide the "Reactions" column. */
    .dataTable th:nth-child(5), td:nth-child(5) { display: none !important; }

    /* Add 1px horizontal space around avatars in the Cmntrs column. */
    .dataTable td:nth-child(9) img { margin-left: 1px !important; margin-right: 1px !important; }

    /* Adjust the look & feel of the GitHub tags. */
    .gh-label, .gh-tag { border-radius: 6px; }
    .gh-tag { padding: 3px !important; border: 1px dotted #333333; border-radius: 6px; }

    /* Right-align the "Tags" column (the last column) and rename it to "Status". */
    td.cell-tags, .tags-col, .col-tags, .tags-col > div, .col-tags > div { text-align: right !important; justify-content: display: flex !important; flex-start !important; justify-content: flex-end !important; flex-wrap: wrap !important; }
    th.tags-col, th:last-child { text-align: right !important; }

    /* Adjust the Triage Party tags (the ones in the last column). */
    .tag-pr-unreviewed, .tag-pr-new-commits, .tag-recv { background-color: #ffffff !important; color: orange !important; }
    .tag-commented { display: none !important; }
    .tag-author-last { display: none !important; }
    .tag-member-last { display: none !important; }
    .tag-pr-merged { display: none !important; }
    .tag-pr-closed { display: none !important; }
    .tag-open-milestone { display: none !important; }
    .tag-assigned { display: none !important; }
    .tag-assignee-updated { display: none !important; }
    .tag-contributor-last { display: none !important; }
    .tag-collaborator-last { display: none !important; }
    .tag-similar { display: none !important; }
    .tag-assigned { background-color: transparent !important; color: #222 !important; border: 1px dotted #333333; border-radius: 6px; }
    .tag-send { visibility: hidden !important; position: relative; }
    .tag-send::after { visibility: visible; content: "Last comment: team"; color: darkolivegreen !important; border: 1px dotted #333333; border-radius: 6px; }
    .tag-recv { visibility: hidden !important; position: relative; }
    .tag-recv::after { visibility: visible; content: "Last comment: author"; color: darkorange !important; border: 1px dotted #333333; border-radius: 6px; }
    .tag-recv-q { visibility: hidden !important; position: relative; }
    .tag-recv-q::after { visibility: visible; content: "Question waiting"; background-color: wheat !important; color: purple !important; border: 1px dotted #333333; border-radius: 6px; }
    .tag-approved, .tag-pr-approved { visibility: hidden !important; position: relative; }
    .tag-approved::after, .tag-pr-approved::after { visibility: visible; content: "PR approved"; color: green !important; border: 1px dotted #333333; border-radius: 6px; }
    .tag-unreviewed { visibility: hidden !important; position: relative; }
    .tag-unreviewed::after { visibility: visible; content: "PR needs review"; color: red !important; border: 1px dotted #333333; border-radius: 6px; }
    .tag-pr-unreviewed { visibility: hidden !important; position: relative; }
    .tag-pr-unreviewed::after { visibility: visible; content: "PR needs review"; color: red !important; border: 1px dotted #333333; border-radius: 6px; }
    .tag-new-commits { visibility: hidden !important; position: relative; }
    .tag-new-commits::after { visibility: visible; content: "New commits"; color: purple !important; background-color: transparent !important; border: 1px dotted #333333; border-radius: 6px; }
    .tag-pr-new-commits { visibility: hidden !important; position: relative; }
    .tag-pr-new-commits::after { visibility: visible; content: "PR new commits"; color: pink !important; border: 1px dotted #333333; border-radius: 6px; }
