apiVersion: apps/v1
kind: Deployment
metadata:
  name: triage-party
  namespace: triage-party
spec:
  selector:
    matchLabels:
      app: triage-party
  template:
    metadata:
      labels:
        app: triage-party
    spec:
      containers:
      - name: triage-party
        image: triageparty/triage-party
        imagePullPolicy: Always
        args: ["/app/main", "--min-refresh","2m", "--max-refresh", "2m"]
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: triage-party-github-token
              key: token
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: custom-css-volume
          mountPath: /app/site/static/css/custom.css
          subPath: custom.css
        - name: favicon-volume
          mountPath: /app/site/static/img/favicon-32x32.png
          subPath: favicon-32x32.png
      volumes:
      - name: config
        configMap:
          name: triage-party-config
      - name: custom-css-volume
        configMap:
          name: cirq-triage-party-css
      - name: favicon-volume
        configMap:
          name: triage-party-favicon
