proto_library(
    name = "metrics_proto",
    srcs = ["metrics.proto"],
)

proto_library(
    name = "program_proto",
    srcs = ["program.proto"],
)

proto_library(
    name = "result_proto",
    srcs = ["result.proto"],
    deps = [
        "program_proto",
    ],
)

proto_library(
    name = "run_context_proto",
    srcs = ["run_contex.proto"],
)
