# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import google.protobuf.internal.containers
import google.protobuf.message
import typing

class DeviceSpecification(google.protobuf.message.Message):
    valid_qubits = ... # type: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]
    developer_recommendations = ... # type: typing.Text

    @property
    def valid_gate_sets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[GateSet]: ...

    @property
    def valid_targets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[TargetSet]: ...

    def __init__(self,
        valid_gate_sets : typing.Optional[typing.Iterable[GateSet]] = None,
        valid_qubits : typing.Optional[typing.Iterable[typing.Text]] = None,
        valid_targets : typing.Optional[typing.Iterable[TargetSet]] = None,
        developer_recommendations : typing.Optional[typing.Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> DeviceSpecification: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...

class GateSet(google.protobuf.message.Message):
    name = ... # type: typing.Text

    @property
    def valid_gates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[GateDefinition]: ...

    def __init__(self,
        name : typing.Optional[typing.Text] = None,
        valid_gates : typing.Optional[typing.Iterable[GateDefinition]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GateSet: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...

class GateDefinition(google.protobuf.message.Message):
    id = ... # type: typing.Text
    number_of_qubits = ... # type: int
    gate_duration_picos = ... # type: int
    valid_targets = ... # type: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]

    @property
    def valid_args(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ArgDefinition]: ...

    def __init__(self,
        id : typing.Optional[typing.Text] = None,
        number_of_qubits : typing.Optional[int] = None,
        valid_args : typing.Optional[typing.Iterable[ArgDefinition]] = None,
        gate_duration_picos : typing.Optional[int] = None,
        valid_targets : typing.Optional[typing.Iterable[typing.Text]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GateDefinition: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...

class ArgDefinition(google.protobuf.message.Message):
    class ArgType(int):
        @classmethod
        def Name(cls, number: int) -> str: ...
        @classmethod
        def Value(cls, name: str) -> int: ...
        @classmethod
        def keys(cls) -> typing.List[str]: ...
        @classmethod
        def values(cls) -> typing.List[int]: ...
        @classmethod
        def items(cls) -> typing.List[typing.Tuple[str, int]]: ...
    UNSPECIFIED = typing.cast(ArgType, 0)
    FLOAT = typing.cast(ArgType, 1)
    REPEATED_BOOLEAN = typing.cast(ArgType, 2)
    STRING = typing.cast(ArgType, 3)

    name = ... # type: typing.Text
    type = ... # type: ArgDefinition.ArgType

    @property
    def allowed_ranges(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ArgumentRange]: ...

    def __init__(self,
        name : typing.Optional[typing.Text] = None,
        type : typing.Optional[ArgDefinition.ArgType] = None,
        allowed_ranges : typing.Optional[typing.Iterable[ArgumentRange]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ArgDefinition: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...

class ArgumentRange(google.protobuf.message.Message):
    minimum_value = ... # type: float
    maximum_value = ... # type: float

    def __init__(self,
        minimum_value : typing.Optional[float] = None,
        maximum_value : typing.Optional[float] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ArgumentRange: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...

class TargetSet(google.protobuf.message.Message):
    class TargetOrdering(int):
        @classmethod
        def Name(cls, number: int) -> str: ...
        @classmethod
        def Value(cls, name: str) -> int: ...
        @classmethod
        def keys(cls) -> typing.List[str]: ...
        @classmethod
        def values(cls) -> typing.List[int]: ...
        @classmethod
        def items(cls) -> typing.List[typing.Tuple[str, int]]: ...
    UNSPECIFIED = typing.cast(TargetOrdering, 0)
    SYMMETRIC = typing.cast(TargetOrdering, 1)
    ASYMMETRIC = typing.cast(TargetOrdering, 2)
    SUBSET_PERMUTATION = typing.cast(TargetOrdering, 3)

    name = ... # type: typing.Text
    target_ordering = ... # type: TargetSet.TargetOrdering

    @property
    def targets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Target]: ...

    def __init__(self,
        name : typing.Optional[typing.Text] = None,
        target_ordering : typing.Optional[TargetSet.TargetOrdering] = None,
        targets : typing.Optional[typing.Iterable[Target]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> TargetSet: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...

class Target(google.protobuf.message.Message):
    ids = ... # type: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]

    def __init__(self,
        ids : typing.Optional[typing.Iterable[typing.Text]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Target: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
