# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class DeviceSpecification(google___protobuf___message___Message):
    valid_qubits = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    developer_recommendations = ... # type: typing___Text

    @property
    def valid_gate_sets(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[GateSet]: ...

    @property
    def valid_targets(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[TargetSet]: ...

    def __init__(self,
        valid_gate_sets : typing___Optional[typing___Iterable[GateSet]] = None,
        valid_qubits : typing___Optional[typing___Iterable[typing___Text]] = None,
        valid_targets : typing___Optional[typing___Iterable[TargetSet]] = None,
        developer_recommendations : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> DeviceSpecification: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"developer_recommendations",u"valid_gate_sets",u"valid_qubits",u"valid_targets"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"developer_recommendations",b"valid_gate_sets",b"valid_qubits",b"valid_targets"]) -> None: ...

class GateSet(google___protobuf___message___Message):
    name = ... # type: typing___Text

    @property
    def valid_gates(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[GateDefinition]: ...

    def __init__(self,
        name : typing___Optional[typing___Text] = None,
        valid_gates : typing___Optional[typing___Iterable[GateDefinition]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GateSet: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"name",u"valid_gates"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"name",b"valid_gates"]) -> None: ...

class GateDefinition(google___protobuf___message___Message):
    id = ... # type: typing___Text
    number_of_qubits = ... # type: int
    gate_duration_picos = ... # type: int
    valid_targets = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]

    @property
    def valid_args(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ArgDefinition]: ...

    def __init__(self,
        id : typing___Optional[typing___Text] = None,
        number_of_qubits : typing___Optional[int] = None,
        valid_args : typing___Optional[typing___Iterable[ArgDefinition]] = None,
        gate_duration_picos : typing___Optional[int] = None,
        valid_targets : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GateDefinition: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"gate_duration_picos",u"id",u"number_of_qubits",u"valid_args",u"valid_targets"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"gate_duration_picos",b"id",b"number_of_qubits",b"valid_args",b"valid_targets"]) -> None: ...

class ArgDefinition(google___protobuf___message___Message):
    class ArgType(int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: int) -> str: ...
        @classmethod
        def Value(cls, name: str) -> ArgDefinition.ArgType: ...
        @classmethod
        def keys(cls) -> typing___List[str]: ...
        @classmethod
        def values(cls) -> typing___List[ArgDefinition.ArgType]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[str, ArgDefinition.ArgType]]: ...
    UNSPECIFIED = typing___cast(ArgType, 0)
    FLOAT = typing___cast(ArgType, 1)
    REPEATED_BOOLEAN = typing___cast(ArgType, 2)
    STRING = typing___cast(ArgType, 3)

    name = ... # type: typing___Text
    type = ... # type: ArgDefinition.ArgType

    @property
    def allowed_ranges(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ArgumentRange]: ...

    def __init__(self,
        name : typing___Optional[typing___Text] = None,
        type : typing___Optional[ArgDefinition.ArgType] = None,
        allowed_ranges : typing___Optional[typing___Iterable[ArgumentRange]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ArgDefinition: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"allowed_ranges",u"name",u"type"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"allowed_ranges",b"name",b"type"]) -> None: ...

class ArgumentRange(google___protobuf___message___Message):
    minimum_value = ... # type: float
    maximum_value = ... # type: float

    def __init__(self,
        minimum_value : typing___Optional[float] = None,
        maximum_value : typing___Optional[float] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ArgumentRange: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"maximum_value",u"minimum_value"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"maximum_value",b"minimum_value"]) -> None: ...

class TargetSet(google___protobuf___message___Message):
    class TargetOrdering(int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: int) -> str: ...
        @classmethod
        def Value(cls, name: str) -> TargetSet.TargetOrdering: ...
        @classmethod
        def keys(cls) -> typing___List[str]: ...
        @classmethod
        def values(cls) -> typing___List[TargetSet.TargetOrdering]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[str, TargetSet.TargetOrdering]]: ...
    UNSPECIFIED = typing___cast(TargetOrdering, 0)
    SYMMETRIC = typing___cast(TargetOrdering, 1)
    ASYMMETRIC = typing___cast(TargetOrdering, 2)
    SUBSET_PERMUTATION = typing___cast(TargetOrdering, 3)

    name = ... # type: typing___Text
    target_ordering = ... # type: TargetSet.TargetOrdering

    @property
    def targets(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Target]: ...

    def __init__(self,
        name : typing___Optional[typing___Text] = None,
        target_ordering : typing___Optional[TargetSet.TargetOrdering] = None,
        targets : typing___Optional[typing___Iterable[Target]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> TargetSet: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"name",u"target_ordering",u"targets"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"name",b"target_ordering",b"targets"]) -> None: ...

class Target(google___protobuf___message___Message):
    ids = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]

    def __init__(self,
        ids : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Target: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"ids"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"ids"]) -> None: ...
