name: Daily Integration Check

on:
  schedule:
  - cron: "0 14 * * *"  # Daily at 14:00 UTC
  workflow_dispatch:  # so that we can also run manually, e.g. for testing


jobs:
  daily-integration-check:
    name: Pytest integration check
    env:
      TEST_USER_TOKEN : ${{ secrets.TEST_USER_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
      - name: Pytest integration check
        run: |
          check/pytest-daily-integration
