# This publishes to PyPI. See: https://github.com/pypa/gh-action-pypi-publish
name: Publish cirq-superstaq to PyPI
on:
  workflow_dispatch: null
jobs:
  docs:
    name: publish to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        env:
          PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
        run: |
          python -m pip install twine
          python -m pip install wheel
          dev_tools/update-version.sh
