# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import google.protobuf.internal.containers
import google.protobuf.message
import typing

class MetricsSnapshot(google.protobuf.message.Message):
    timestamp_ms = ... # type: int

    @property
    def metrics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Metric]: ...

    def __init__(self,
        timestamp_ms : typing.Optional[int] = None,
        metrics : typing.Optional[typing.Iterable[Metric]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> MetricsSnapshot: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...

class Metric(google.protobuf.message.Message):
    name = ... # type: typing.Text
    targets = ... # type: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]

    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Value]: ...

    def __init__(self,
        name : typing.Optional[typing.Text] = None,
        targets : typing.Optional[typing.Iterable[typing.Text]] = None,
        values : typing.Optional[typing.Iterable[Value]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Metric: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...

class Value(google.protobuf.message.Message):
    double_val = ... # type: float
    int32_val = ... # type: int
    int64_val = ... # type: int
    str_val = ... # type: typing.Text

    def __init__(self,
        double_val : typing.Optional[float] = None,
        int32_val : typing.Optional[int] = None,
        int64_val : typing.Optional[int] = None,
        str_val : typing.Optional[typing.Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Value: ...
    def MergeFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
    def CopyFrom(self, other_msg: google.protobuf.message.Message) -> None: ...
