# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cirq_google/api/v2/batch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import program_pb2 as cirq__google_dot_api_dot_v2_dot_program__pb2
from . import result_pb2 as cirq__google_dot_api_dot_v2_dot_result__pb2
from . import run_context_pb2 as cirq__google_dot_api_dot_v2_dot_run__context__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63irq_google/api/v2/batch.proto\x12\x12\x63irq.google.api.v2\x1a cirq_google/api/v2/program.proto\x1a\x1f\x63irq_google/api/v2/result.proto\x1a$cirq_google/api/v2/run_context.proto\"=\n\x0c\x42\x61tchProgram\x12-\n\x08programs\x18\x01 \x03(\x0b\x32\x1b.cirq.google.api.v2.Program\"G\n\x0f\x42\x61tchRunContext\x12\x34\n\x0crun_contexts\x18\x01 \x03(\x0b\x32\x1e.cirq.google.api.v2.RunContext\":\n\x0b\x42\x61tchResult\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.cirq.google.api.v2.ResultB-\n\x1d\x63om.google.cirq.google.api.v2B\nBatchProtoP\x01\x62\x06proto3')



_BATCHPROGRAM = DESCRIPTOR.message_types_by_name['BatchProgram']
_BATCHRUNCONTEXT = DESCRIPTOR.message_types_by_name['BatchRunContext']
_BATCHRESULT = DESCRIPTOR.message_types_by_name['BatchResult']
BatchProgram = _reflection.GeneratedProtocolMessageType('BatchProgram', (_message.Message,), {
  'DESCRIPTOR' : _BATCHPROGRAM,
  '__module__' : 'cirq_google.api.v2.batch_pb2'
  # @@protoc_insertion_point(class_scope:cirq.google.api.v2.BatchProgram)
  })
_sym_db.RegisterMessage(BatchProgram)

BatchRunContext = _reflection.GeneratedProtocolMessageType('BatchRunContext', (_message.Message,), {
  'DESCRIPTOR' : _BATCHRUNCONTEXT,
  '__module__' : 'cirq_google.api.v2.batch_pb2'
  # @@protoc_insertion_point(class_scope:cirq.google.api.v2.BatchRunContext)
  })
_sym_db.RegisterMessage(BatchRunContext)

BatchResult = _reflection.GeneratedProtocolMessageType('BatchResult', (_message.Message,), {
  'DESCRIPTOR' : _BATCHRESULT,
  '__module__' : 'cirq_google.api.v2.batch_pb2'
  # @@protoc_insertion_point(class_scope:cirq.google.api.v2.BatchResult)
  })
_sym_db.RegisterMessage(BatchResult)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.google.cirq.google.api.v2B\nBatchProtoP\001'
  _BATCHPROGRAM._serialized_start=159
  _BATCHPROGRAM._serialized_end=220
  _BATCHRUNCONTEXT._serialized_start=222
  _BATCHRUNCONTEXT._serialized_end=293
  _BATCHRESULT._serialized_start=295
  _BATCHRESULT._serialized_end=353
# @@protoc_insertion_point(module_scope)
