# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cirq_google/api/v2/run_context.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$cirq_google/api/v2/run_context.proto\x12\x12\x63irq.google.api.v2\"J\n\nRunContext\x12<\n\x10parameter_sweeps\x18\x01 \x03(\x0b\x32\".cirq.google.api.v2.ParameterSweep\"O\n\x0eParameterSweep\x12\x13\n\x0brepetitions\x18\x01 \x01(\x05\x12(\n\x05sweep\x18\x02 \x01(\x0b\x32\x19.cirq.google.api.v2.Sweep\"\x86\x01\n\x05Sweep\x12;\n\x0esweep_function\x18\x01 \x01(\x0b\x32!.cirq.google.api.v2.SweepFunctionH\x00\x12\x37\n\x0csingle_sweep\x18\x02 \x01(\x0b\x32\x1f.cirq.google.api.v2.SingleSweepH\x00\x42\x07\n\x05sweep\"\xc6\x01\n\rSweepFunction\x12\x45\n\rfunction_type\x18\x01 \x01(\x0e\x32..cirq.google.api.v2.SweepFunction.FunctionType\x12)\n\x06sweeps\x18\x02 \x03(\x0b\x32\x19.cirq.google.api.v2.Sweep\"C\n\x0c\x46unctionType\x12\x1d\n\x19\x46UNCTION_TYPE_UNSPECIFIED\x10\x00\x12\x0b\n\x07PRODUCT\x10\x01\x12\x07\n\x03ZIP\x10\x02\";\n\x0f\x44\x65viceParameter\x12\x0c\n\x04path\x18\x01 \x03(\t\x12\x0b\n\x03idx\x18\x02 \x01(\x03\x12\r\n\x05units\x18\x03 \x01(\t\"\xc5\x01\n\x0bSingleSweep\x12\x15\n\rparameter_key\x18\x01 \x01(\t\x12,\n\x06points\x18\x02 \x01(\x0b\x32\x1a.cirq.google.api.v2.PointsH\x00\x12\x30\n\x08linspace\x18\x03 \x01(\x0b\x32\x1c.cirq.google.api.v2.LinspaceH\x00\x12\x36\n\tparameter\x18\x04 \x01(\x0b\x32#.cirq.google.api.v2.DeviceParameterB\x07\n\x05sweep\"\x18\n\x06Points\x12\x0e\n\x06points\x18\x01 \x03(\x02\"G\n\x08Linspace\x12\x13\n\x0b\x66irst_point\x18\x01 \x01(\x02\x12\x12\n\nlast_point\x18\x02 \x01(\x02\x12\x12\n\nnum_points\x18\x03 \x01(\x03\x42\x32\n\x1d\x63om.google.cirq.google.api.v2B\x0fRunContextProtoP\x01\x62\x06proto3')



_RUNCONTEXT = DESCRIPTOR.message_types_by_name['RunContext']
_PARAMETERSWEEP = DESCRIPTOR.message_types_by_name['ParameterSweep']
_SWEEP = DESCRIPTOR.message_types_by_name['Sweep']
_SWEEPFUNCTION = DESCRIPTOR.message_types_by_name['SweepFunction']
_DEVICEPARAMETER = DESCRIPTOR.message_types_by_name['DeviceParameter']
_SINGLESWEEP = DESCRIPTOR.message_types_by_name['SingleSweep']
_POINTS = DESCRIPTOR.message_types_by_name['Points']
_LINSPACE = DESCRIPTOR.message_types_by_name['Linspace']
_SWEEPFUNCTION_FUNCTIONTYPE = _SWEEPFUNCTION.enum_types_by_name['FunctionType']
RunContext = _reflection.GeneratedProtocolMessageType('RunContext', (_message.Message,), {
  'DESCRIPTOR' : _RUNCONTEXT,
  '__module__' : 'cirq_google.api.v2.run_context_pb2'
  # @@protoc_insertion_point(class_scope:cirq.google.api.v2.RunContext)
  })
_sym_db.RegisterMessage(RunContext)

ParameterSweep = _reflection.GeneratedProtocolMessageType('ParameterSweep', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERSWEEP,
  '__module__' : 'cirq_google.api.v2.run_context_pb2'
  # @@protoc_insertion_point(class_scope:cirq.google.api.v2.ParameterSweep)
  })
_sym_db.RegisterMessage(ParameterSweep)

Sweep = _reflection.GeneratedProtocolMessageType('Sweep', (_message.Message,), {
  'DESCRIPTOR' : _SWEEP,
  '__module__' : 'cirq_google.api.v2.run_context_pb2'
  # @@protoc_insertion_point(class_scope:cirq.google.api.v2.Sweep)
  })
_sym_db.RegisterMessage(Sweep)

SweepFunction = _reflection.GeneratedProtocolMessageType('SweepFunction', (_message.Message,), {
  'DESCRIPTOR' : _SWEEPFUNCTION,
  '__module__' : 'cirq_google.api.v2.run_context_pb2'
  # @@protoc_insertion_point(class_scope:cirq.google.api.v2.SweepFunction)
  })
_sym_db.RegisterMessage(SweepFunction)

DeviceParameter = _reflection.GeneratedProtocolMessageType('DeviceParameter', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEPARAMETER,
  '__module__' : 'cirq_google.api.v2.run_context_pb2'
  # @@protoc_insertion_point(class_scope:cirq.google.api.v2.DeviceParameter)
  })
_sym_db.RegisterMessage(DeviceParameter)

SingleSweep = _reflection.GeneratedProtocolMessageType('SingleSweep', (_message.Message,), {
  'DESCRIPTOR' : _SINGLESWEEP,
  '__module__' : 'cirq_google.api.v2.run_context_pb2'
  # @@protoc_insertion_point(class_scope:cirq.google.api.v2.SingleSweep)
  })
_sym_db.RegisterMessage(SingleSweep)

Points = _reflection.GeneratedProtocolMessageType('Points', (_message.Message,), {
  'DESCRIPTOR' : _POINTS,
  '__module__' : 'cirq_google.api.v2.run_context_pb2'
  # @@protoc_insertion_point(class_scope:cirq.google.api.v2.Points)
  })
_sym_db.RegisterMessage(Points)

Linspace = _reflection.GeneratedProtocolMessageType('Linspace', (_message.Message,), {
  'DESCRIPTOR' : _LINSPACE,
  '__module__' : 'cirq_google.api.v2.run_context_pb2'
  # @@protoc_insertion_point(class_scope:cirq.google.api.v2.Linspace)
  })
_sym_db.RegisterMessage(Linspace)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.google.cirq.google.api.v2B\017RunContextProtoP\001'
  _RUNCONTEXT._serialized_start=60
  _RUNCONTEXT._serialized_end=134
  _PARAMETERSWEEP._serialized_start=136
  _PARAMETERSWEEP._serialized_end=215
  _SWEEP._serialized_start=218
  _SWEEP._serialized_end=352
  _SWEEPFUNCTION._serialized_start=355
  _SWEEPFUNCTION._serialized_end=553
  _SWEEPFUNCTION_FUNCTIONTYPE._serialized_start=486
  _SWEEPFUNCTION_FUNCTIONTYPE._serialized_end=553
  _DEVICEPARAMETER._serialized_start=555
  _DEVICEPARAMETER._serialized_end=614
  _SINGLESWEEP._serialized_start=617
  _SINGLESWEEP._serialized_end=814
  _POINTS._serialized_start=816
  _POINTS._serialized_end=840
  _LINSPACE._serialized_start=842
  _LINSPACE._serialized_end=913
# @@protoc_insertion_point(module_scope)
