apiVersion: v1
kind: Service
metadata:
  name: cirq-pr-monitor-headless-svc
  labels:
    app: cirq-pr-monitor
spec:
  clusterIP: None
  selector:
    app: cirq-pr-monitor
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cirq-pr-monitor
spec:
  selector:
    matchLabels:
      app: cirq-pr-monitor
  serviceName: automerge-headless-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: cirq-pr-monitor
    spec:
      containers:
      - name: cirq-pr-monitor
        image: us-docker.pkg.dev/cirq-infra/cirq/pr_monitor
