proto_library(
    name = "operations_proto",
    srcs = ["operations.proto"],
)

proto_library(
    name = "params_proto",
    srcs = ["params.proto"],
)

proto_library(
    name = "program_proto",
    srcs = ["program.proto"],
    deps = [
    "operations_proto",
    "params_proto",
    ],
)
